name: My second workflow
on: 
    workflow_dispatch
jobs:
  second job:
   runs-on: ubuntu latest
   steps:
    - name: Printing two messages
      run: |
       echo "hello this is my second message"
       echo "*********************************"
    - name: event name
      run: echo "event name is : ${{ github.event_name }}"

      
